version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/usr/src/app

  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgressql/data
  
  test_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_database
      - DATABASE_HOST = postgres_db_2
    ports:
      - '6543:6543'
    volumes:
      - postgres-db:/var/lib/postgressql/test
  
  redis:
    image: redis:latest
    container_name: redis_risevest
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

volumes:
  postgres-db:
  redis_volume_data: